### ISSUE TITLE
Fixing scp root@IP_SERVER

### ISSUE THREAD

**Issue by pascalandy** [kolargol/openvpn#2]
First, I want to say thank you! You doc is solid! 

I little fix I had to do was:

`scp root@IP_SERVER:/etc/openvpn/export/archives/privateVPN-Desktop-JohnDoe.tar.gz ./privateVPN-Desktop-JohnDoe.tar.gz` insteawd of `scp root@SERVER_IP:/etc/openvpn/export/archives/* .`

**Comment by kolargol** [comment]
scp with wildcard copy did not worked for you ?

**Comment by pascalandy** [comment]
No it did not. So I tried with one file at a time and it worked :)

**Comment by kolargol** [comment]
what is your OS?

**Comment by pascalandy** [comment]
Mac El Captain 10.11.6
iterm

**Comment by kolargol** [comment]
I cannot reproduce problem, file name expansion should work as expected.
